// <auto-generated />
using System;
using LogicaAccesoDatos.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogicaAccesoDatos.Migrations
{
    [DbContext(typeof(GestionOperacionesDbContext))]
    partial class GestionOperacionesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LogicaNegocio.Entidades.Asunto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NombreCliente");

                    b.Property<int>("Nomenclatura")
                        .HasColumnType("int")
                        .HasColumnName("Nomenclatura");

                    b.Property<int?>("NroCarpeta")
                        .HasColumnType("int")
                        .HasColumnName("NroCarpeta");

                    b.Property<int?>("NroDua")
                        .HasColumnType("int")
                        .HasColumnName("NroDua");

                    b.HasKey("Id");

                    b.ToTable("Asuntos", (string)null);
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Comunicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AsuntoId")
                        .HasColumnType("int");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Contenido");

                    b.Property<bool>("Enviado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("Enviado");

                    b.Property<DateTime>("FechaEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2026, 4, 28, 23, 52, 18, 615, DateTimeKind.Local).AddTicks(498))
                        .HasColumnName("FechaEnvio");

                    b.Property<int?>("OperacionId")
                        .HasColumnType("int");

                    b.Property<int>("TipoComunicacionId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioEnvioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AsuntoId");

                    b.HasIndex("OperacionId");

                    b.HasIndex("TipoComunicacionId");

                    b.HasIndex("UsuarioEnvioId");

                    b.ToTable("Comunicaciones", (string)null);
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.DetalleLiquidacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Descripcion");

                    b.Property<int>("LiquidacionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Monto");

                    b.HasKey("Id");

                    b.HasIndex("LiquidacionId");

                    b.ToTable("DetallesLiquidacion", (string)null);
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCarga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2026, 4, 28, 23, 52, 18, 609, DateTimeKind.Local).AddTicks(1162))
                        .HasColumnName("FechaCarga");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Formato");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Nombre");

                    b.Property<int>("OperacionId")
                        .HasColumnType("int");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("RutaArchivo");

                    b.HasKey("Id");

                    b.HasIndex("OperacionId");

                    b.ToTable("Documentos", (string)null);
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCarga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2026, 4, 28, 23, 52, 18, 613, DateTimeKind.Local).AddTicks(6112))
                        .HasColumnName("FechaCarga");

                    b.Property<int>("LiquidacionId")
                        .HasColumnType("int");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("RutaArchivo");

                    b.HasKey("Id");

                    b.HasIndex("LiquidacionId")
                        .IsUnique();

                    b.ToTable("Facturas", (string)null);
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Liquidacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("Estado");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaEnvio");

                    b.Property<DateTime>("FechaVenc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaVenc");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MontoTotal");

                    b.Property<int>("OperacionId")
                        .HasColumnType("int");

                    b.Property<decimal>("SaldoPendiente")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SaldoPendiente");

                    b.HasKey("Id");

                    b.HasIndex("OperacionId");

                    b.ToTable("Liquidaciones", (string)null);
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Operacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("Estado");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2026, 4, 28, 23, 52, 18, 605, DateTimeKind.Local).AddTicks(7884))
                        .HasColumnName("FechaRegistro");

                    b.Property<string>("NroCarpeta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NroCarpeta");

                    b.Property<int?>("NroConocimiento")
                        .HasColumnType("int")
                        .HasColumnName("NroConocimiento");

                    b.Property<string>("NroDua")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NroDua");

                    b.Property<int?>("TipoConocimientoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoOperacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("NroCarpeta")
                        .IsUnique()
                        .HasDatabaseName("IX_Operaciones_NroCarpeta_Unique");

                    b.HasIndex("TipoConocimientoId");

                    b.HasIndex("TipoOperacionId");

                    b.ToTable("Operaciones", (string)null);
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Estado");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaPago");

                    b.Property<string>("IdTransaccion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("IdTransaccion");

                    b.Property<int>("LiquidacionId")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MontoPagado");

                    b.Property<string>("RutaComprobante")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("RutaComprobante");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("Tipo");

                    b.HasKey("Id");

                    b.HasIndex("LiquidacionId");

                    b.ToTable("Pagos", (string)null);
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NombreRol");

                    b.HasKey("Id");

                    b.HasIndex("NombreRol")
                        .IsUnique()
                        .HasDatabaseName("IX_Roles_NombreRol_Unique");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NombreRol = "Despachante"
                        },
                        new
                        {
                            Id = 2,
                            NombreRol = "Cliente"
                        },
                        new
                        {
                            Id = 3,
                            NombreRol = "Asistente"
                        });
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.TipoComunicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AsuntoId")
                        .HasColumnType("int");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Contenido");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Descripcion");

                    b.HasKey("Id");

                    b.HasIndex("AsuntoId");

                    b.ToTable("TiposComunicacion", (string)null);
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.TipoConocimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Descripcion");

                    b.HasKey("Id");

                    b.HasIndex("Descripcion")
                        .IsUnique()
                        .HasDatabaseName("IX_TiposConocimiento_Descripcion_Unique");

                    b.ToTable("TiposConocimiento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Conocimiento de Embarque Marítimo"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Guía Aérea"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Carta de Porte Terrestre"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Declaración de Tránsito"
                        });
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.TipoOperacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Descripcion");

                    b.HasKey("Id");

                    b.HasIndex("Descripcion")
                        .IsUnique()
                        .HasDatabaseName("IX_TiposOperacion_Descripcion_Unique");

                    b.ToTable("TiposOperacion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Importación"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Exportación"
                        });
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Apellido");

                    b.Property<int>("Discriminator")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios", (string)null);

                    b.HasDiscriminator<int>("Discriminator").HasValue(0);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.ValidacionPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aprobado")
                        .HasColumnType("bit")
                        .HasColumnName("Aprobado");

                    b.Property<DateTime>("FechaValidacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2026, 4, 28, 23, 52, 18, 612, DateTimeKind.Local).AddTicks(6241))
                        .HasColumnName("FechaValidacion");

                    b.Property<string>("MotivoRechazo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MotivoRechazo");

                    b.Property<int>("PagoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioValidacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PagoId")
                        .IsUnique();

                    b.HasIndex("UsuarioValidacionId");

                    b.ToTable("ValidacionesPago", (string)null);
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Cliente", b =>
                {
                    b.HasBaseType("LogicaNegocio.Entidades.Usuario");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Direccion");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("RUT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Telefono");

                    b.HasIndex("Rut")
                        .IsUnique()
                        .HasDatabaseName("IX_Clientes_RUT_Unique")
                        .HasFilter("[RUT] IS NOT NULL");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Despachante", b =>
                {
                    b.HasBaseType("LogicaNegocio.Entidades.Usuario");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("RUT");

                    b.HasIndex("Rut")
                        .IsUnique()
                        .HasDatabaseName("IX_Despachantes_RUT_Unique")
                        .HasFilter("[RUT] IS NOT NULL");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Comunicacion", b =>
                {
                    b.HasOne("LogicaNegocio.Entidades.Asunto", "Asunto")
                        .WithMany()
                        .HasForeignKey("AsuntoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogicaNegocio.Entidades.Operacion", "Operacion")
                        .WithMany("Comunicaciones")
                        .HasForeignKey("OperacionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LogicaNegocio.Entidades.TipoComunicacion", "TipoComunicacion")
                        .WithMany()
                        .HasForeignKey("TipoComunicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogicaNegocio.Entidades.Usuario", "UsuarioEnvio")
                        .WithMany()
                        .HasForeignKey("UsuarioEnvioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asunto");

                    b.Navigation("Operacion");

                    b.Navigation("TipoComunicacion");

                    b.Navigation("UsuarioEnvio");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.DetalleLiquidacion", b =>
                {
                    b.HasOne("LogicaNegocio.Entidades.Liquidacion", "Liquidacion")
                        .WithMany("Detalle")
                        .HasForeignKey("LiquidacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Liquidacion");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Documento", b =>
                {
                    b.HasOne("LogicaNegocio.Entidades.Operacion", "Operacion")
                        .WithMany("Documentos")
                        .HasForeignKey("OperacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operacion");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Factura", b =>
                {
                    b.HasOne("LogicaNegocio.Entidades.Liquidacion", "Liquidacion")
                        .WithOne("Factura")
                        .HasForeignKey("LogicaNegocio.Entidades.Factura", "LiquidacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Liquidacion");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Liquidacion", b =>
                {
                    b.HasOne("LogicaNegocio.Entidades.Operacion", "Operacion")
                        .WithMany("Liquidaciones")
                        .HasForeignKey("OperacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operacion");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Operacion", b =>
                {
                    b.HasOne("LogicaNegocio.Entidades.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogicaNegocio.Entidades.TipoConocimiento", "TipoConocimiento")
                        .WithMany()
                        .HasForeignKey("TipoConocimientoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LogicaNegocio.Entidades.TipoOperacion", "TipoOperacion")
                        .WithMany()
                        .HasForeignKey("TipoOperacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("TipoConocimiento");

                    b.Navigation("TipoOperacion");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Pago", b =>
                {
                    b.HasOne("LogicaNegocio.Entidades.Liquidacion", "Liquidacion")
                        .WithMany("Pagos")
                        .HasForeignKey("LiquidacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Liquidacion");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.TipoComunicacion", b =>
                {
                    b.HasOne("LogicaNegocio.Entidades.Asunto", "Asunto")
                        .WithMany()
                        .HasForeignKey("AsuntoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asunto");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Usuario", b =>
                {
                    b.HasOne("LogicaNegocio.Entidades.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("LogicaNegocio.ValueObject.Email", "Email", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("Email");

                            b1.HasKey("UsuarioId");

                            b1.HasIndex("Valor")
                                .IsUnique()
                                .HasDatabaseName("IX_Usuarios_Email_Unique");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("LogicaNegocio.ValueObject.Password", "Password", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("PasswordHash");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.ValidacionPago", b =>
                {
                    b.HasOne("LogicaNegocio.Entidades.Pago", "Pago")
                        .WithOne("Validacion")
                        .HasForeignKey("LogicaNegocio.Entidades.ValidacionPago", "PagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogicaNegocio.Entidades.Usuario", "UsuarioValidacion")
                        .WithMany()
                        .HasForeignKey("UsuarioValidacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pago");

                    b.Navigation("UsuarioValidacion");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Liquidacion", b =>
                {
                    b.Navigation("Detalle");

                    b.Navigation("Factura");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Operacion", b =>
                {
                    b.Navigation("Comunicaciones");

                    b.Navigation("Documentos");

                    b.Navigation("Liquidaciones");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Pago", b =>
                {
                    b.Navigation("Validacion");
                });
#pragma warning restore 612, 618
        }
    }
}
